import fs from "fs";
import path from "path";

const POSTS_DIR = "./src/pages/posts/";

// **Posts Criados Manualmente**
const manualPosts = [
    {
      title: "Implementando Automação Industrial com ERP",
      excerpt: "Descubra como integrar sistemas de automação com seu ERP para maximizar a eficiência operacional.",
      category: "Automação",
      date: "2024-02-22",
      image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800",
      slug: "implementar-erp-sucesso"
    },
    {
      title: "Gestão de Estoque em Tempo Real",
      excerpt: "Como utilizar tecnologias modernas para controle preciso de inventário industrial.",
      category: "Gestão",
      date: "2024-02-21",
      image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800",
      slug: "gestao-estoque-tempo-real"
    },
    {
      title: "Análise de Dados na Indústria 4.0",
      excerpt: "O papel do Big Data e Analytics na transformação digital da indústria moderna.",
      category: "Tecnologia",
      date: "2024-02-20",
      image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800",
      slug: "analise-dados-industria-4"
    },
    {
      title: "Manutenção Preditiva com IoT",
      excerpt: "Implementando sensores IoT para prever e prevenir falhas em equipamentos industriais.",
      category: "IoT",
      date: "2024-02-19",
      image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800",
      slug: "manutencao-preditiva-iot"
    },
    {
      title: "Segurança em Sistemas ERP",
      excerpt: "Melhores práticas para proteger dados sensíveis em ambientes industriais.",
      category: "Segurança",
      date: "2024-02-18",
      image: "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?w=800",
      slug: "seguranca-sistemas-erp"
    },
  ];
  
// **Lendo os Posts Criados Automaticamente e Extraindo Dados**
const autoGeneratedPosts = fs
  .readdirSync(POSTS_DIR)
  .filter((file) => file.endsWith(".astro"))
  .map((file) => {
    const filePath = path.join(POSTS_DIR, file);
    const fileContent = fs.readFileSync(filePath, "utf8");

    // Extrai a imagem e a descrição do arquivo .astro gerado
    const titleMatch = fileContent.match(/title: "(.+?)"/);
    const dateMatch = fileContent.match(/date: "(.+?)"/)
    const excerptMatch = fileContent.match(/description: "(.+?)"/);
    const imageMatch = fileContent.match(/urlToImage: "(.+?)"/);

    return {
      title: titleMatch ? titleMatch[1] : file.replace(".astro", "").replace(/-/g, " "),
      excerpt: excerptMatch ? excerptMatch[1] : "Notícia gerada automaticamente.",
      category: "Notícia",
      date: dateMatch ? dateMatch[1] : new Date().toISOString().split("T")[0], // Usa a data atual
      image: imageMatch ? imageMatch[1] : "https://via.placeholder.com/400x200",
      slug: file.replace(".astro", ""),
    };
  });

// **Juntando os posts manuais e automáticos**
export const allPosts = [...manualPosts, ...autoGeneratedPosts];