import fs from "fs";
import path from "path";

const POSTS_DIR = "./src/pages/posts/"; // 📌 Apenas posts da API
const MANUAL_POSTS_DIR = "./src/pages/manual-posts/"; // 📌 Apenas posts manuais

// **Posts Criados Manualmente (Agora Vêm de Arquivos .astro)**
const manualPosts = fs
  .readdirSync(MANUAL_POSTS_DIR)
  .filter((file) => file.endsWith(".astro"))
  .map((file) => {
    const filePath = path.join(MANUAL_POSTS_DIR, file);
    const fileContent = fs.readFileSync(filePath, "utf8");

    // Extrai os dados dos posts manuais
    const titleMatch = fileContent.match(/title: "(.+?)"/);
    const excerptMatch = fileContent.match(/description: "(.+?)"/);
    const imageMatch = fileContent.match(/urlToImage: "(.+?)"/);
    const dateMatch = fileContent.match(/date: "(.+?)"/);

    return {
      title: titleMatch ? titleMatch[1] : file.replace(".astro", "").replace(/-/g, " "),
      excerpt: excerptMatch ? excerptMatch[1] : "Post manual.",
      category: "Manual",
      date: dateMatch ? dateMatch[1] : new Date().toISOString().split("T")[0], // Usa a data real ou a atual
      image: imageMatch ? imageMatch[1] : "https://via.placeholder.com/400x200",
      slug: file.replace(".astro", ""),
    };
  });
  
// **Lendo os Posts Criados Automaticamente e Extraindo Dados**
const autoGeneratedPosts = fs
  .readdirSync(POSTS_DIR)
  .filter((file) => file.endsWith(".astro"))
  .map((file) => {
    const filePath = path.join(POSTS_DIR, file);
    const fileContent = fs.readFileSync(filePath, "utf8");

    // Extrai a imagem e a descrição do arquivo .astro gerado
    const titleMatch = fileContent.match(/title: "(.+?)"/);
    const dateMatch = fileContent.match(/date: "(.+?)"/)
    const excerptMatch = fileContent.match(/description: "(.+?)"/);
    const imageMatch = fileContent.match(/urlToImage: "(.+?)"/);

    return {
      title: titleMatch ? titleMatch[1] : file.replace(".astro", "").replace(/-/g, " "),
      excerpt: excerptMatch ? excerptMatch[1] : "Notícia gerada automaticamente.",
      category: "Notícia",
      date: dateMatch ? dateMatch[1] : new Date().toISOString().split("T")[0], // Usa a data atual
      image: imageMatch ? imageMatch[1] : "https://via.placeholder.com/400x200",
      slug: file.replace(".astro", ""),
    };
  });

// **Juntando os posts manuais e automáticos**
export const allPosts = [...manualPosts, ...autoGeneratedPosts];